REM JP PSX Decoding

l2_actionExtr.exe jp_psx_scripts/CDE0010.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0020.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0030.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0040.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0050.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0060.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0070.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0080.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0090.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0100.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0110.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0120.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0130.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0140.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0160.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0170.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0180.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0190.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0200.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0210.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0240.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0250.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0270.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0280.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0290.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0300.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0310.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0330.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0340.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0345.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0350.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0355.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0360.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0365.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0368.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0370.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0375.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0380.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0390.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0400.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0410.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0420.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0430.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0450.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0460.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0480.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0490.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0500.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0504.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0510.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0520.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0530.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0535.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0537.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0540.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0550.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0560.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0570.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0580.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0590.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0600.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0610.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0615.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0618.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0620.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0630.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0640.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0650.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0660.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0670.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0680.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0690.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0700.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0710.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0720.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0730.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0750.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0760.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0770.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0780.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0790.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0795.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0798.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0800.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0810.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0830.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0835.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0840.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0850.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0860.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0870.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0890.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0900.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0910.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0920.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0930.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0940.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0950.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0960.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0965.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0970.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0975.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0980.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE0990.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1000.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1020.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1030.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1040.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1050.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1060.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1064.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1066.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1068.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1070.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1090.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1100.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1110.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1119.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1120.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1130.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1140.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1145.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1150.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1155.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1158.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1160.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1165.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1167.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1175.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1177.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1180.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1187.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1190.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1195.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1200.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1210.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1230.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1240.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1260.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1270.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1280.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1285.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1290.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1300.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1330.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1340.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1350.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1360.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1370.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1380.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1390.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1405.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1410.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1420.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1425.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1430.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1440.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1445.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1448.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1450.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1460.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1470.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1480.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1490.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1500.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1520.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1545.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1550.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1560.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1600.DAT 1 jp_psx_output 
l2_actionExtr.exe jp_psx_scripts/CDE1650.DAT 1 jp_psx_output 

pause
